apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: xraylab-grafana
  namespace: {{ .Values.global.xraylab.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  deployment:
    skipCreateAdminAccount: true
    {{- if $.Values.global.httpsProxy.enabled }}
    httpProxy:
      enabled: {{ .Values.global.httpsProxy.enabled }}
      noProxy: {{ .Values.global.httpsProxy.noProxy }}
      secureUrl: {{ .Values.global.httpsProxy.secureUrl }}
      url: {{ .Values.global.httpsProxy.url }}
    {{- end }}
    envFrom:
      - secretRef:
          name: grafana-creds
  ingress:
    enabled: true
  config:
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
