kind: ConfigMap
apiVersion: v1
metadata:
  name: config-features
  namespace: knative-serving
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.8.5
data:
  kubernetes.podspec-nodeselector: "enabled"
