apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "3"
  name: job-riskassessment-start-build
  namespace: {{ .Values.global.xraylab.namespace }}
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          oc start-build {{ .Values.buildConfig.name }}
        name: riskassessment-start-new-risk-assessment-image-build
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      activeDeadlineSeconds: 1200
      serviceAccount: {{ .Values.global.xraylab.namespace }}-sa
      serviceAccountName: {{ .Values.global.xraylab.namespace }}-sa
      terminationGracePeriodSeconds: 60
